### ISSUE TITLE
Import Wikidata properties

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-upload#23]
Import Wikidata properties into our local Wikibase instance so that the property numbers are the same

**Comment by rongpenl** [comment]
working on it: [wikibaseTools](https://github.com/usc-isi-i2/wikibaseTools).

**Comment by rongpenl** [comment]
There is a bug in wikibase docker version. the `math` datatype for property can't be recognized. 

Property [P2534](https://www.wikidata.org/wiki/Property_talk:P2534#Supported_environment) seems to be the only one that has this datatype and all `math`-datatype claims are also in its claim.

I am just going to assign the datatype `string` to this edge cases for now.

**Comment by rongpenl** [comment]
Official answer from developer:

> that datatype comes from the Math extension, it looks like the wikibase-docker bundle doesn’t include that extension
no idea how easy or hard it would be to install separately :/
(similarly, the musical notation datatype comes from the Score extension)

math extension [link]( https://github.com/wikimedia/mediawiki-extensions-Math). Will open a new issue.   The first version won't include those datatypes.

**Comment by rongpenl** [comment]
[a usable but non-robust version](https://github.com/usc-isi-i2/wikibaseTools/compare/934f08476a32...a474b257b7fe)
